### ISSUE TITLE
General tracking

### ISSUE THREAD

**Issue by emoon** [emoon/fs-uae#1]
Open an issue here @prb28 if we need to talk more on details without talking in the "catch all" issue over at the main repro

**Comment by emoon** [comment]
Also just wanted to say it's cool that you got it up and running @prb28 As I said before the current debugger implementation in fs-uae can need a bunch of improvements/clean up. Anything you can help out with in this area would be great. I haven't been able to do much work on for a while but my intention is still to come back and doing some work on it but I just don't know when.

**Comment by prb28** [comment]
The debug info helped me:

> AS #12596056/$c0.3358/%110000000011001101011000.00110011.01011000

```AS
start 
00C03358 2c78 0004                     MOVEA.L $00000004,A6
00C0335C 7000                              MOVE.L #$00000000,D0
00C0335E 203c 0000 03e8           MOVE.L #$000003e8,D0
00C03364 223c 0001 0002           MOVE.L #$00010002,D1
```
So the waited offsets are:
- 0
- 4
- 6
- 12
...

These are ok in the debugger and in my file hunk parser, so I think I have a bug somewhere in my vscode extension.

**Comment by emoon** [comment]
Something worth to point out here is that the assembler has also translated `clr.l d0` to `moveq #0,d0` (because this is faster) but I doubt that has anything to do with your code but that instruction should be 2 bytes so the offsets up here that you listed looks correct indeed.

**Comment by prb28** [comment]
Ok, I found my bug, the non synchronous sockets in javascript are making me mad...
There was a mix between the registers response and the memory dump: they have the same message structure and my code is not proceeding them well.
Thank you for the help.

**Comment by emoon** [comment]
Ah I see.

**Comment by prb28** [comment]
Ok this really was a problem with concurrency calls in my debugger.
The fs-uae debugger is not multi-threaded and my code was.
You can close this issue.

**Comment by emoon** [comment]
Alright. You can open (like you did already) individual issues where it makes sense.
